# docker-compose.dev.yml
version: '3.9'

services:
  backend:
    container_name: backend_dev
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: development # Указываем на development-стадию в Dockerfile
    volumes:
      - .:/usr/src/app # Пробрасываем исходный код для hot-reload
      - /usr/src/app/node_modules # Изолируем node_modules в контейнере
    ports:
      - "3000:3000"
      - "9229:9229" # Порт для дебаггера
    env_file:
      - .env.dev
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    container_name: postgres_dev
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network