# docker-compose.dev.yml
version: '3.9'

services:
  backend:
    container_name: backend_dev
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000" # <-- Ваш порт
      - "9229:9229"
    env_file:
      - .env.dev
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    container_name: postgres_dev
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5433:5432" # <-- Ваш порт
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5     start_period: 10s

  postgres:
    container_name: postgres_dev
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "5433:5432" # <-- Ваш порт
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network