version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:17.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-course

volumes:
  postgres_data:

networks:
  payment-course:
