# docker-compose.prod.yml
version: '3.9'

services:
  backend:
    container_name: backend_prod
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: production
    ports:
      - "4000:4000" # <-- Ваш порт
    env_file:
      - .env.prod
    depends_on:
      - postgres
    networks:
      - app_network
    restart: always

  postgres:
    container_name: postgres_prod
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    # В production лучше не открывать порт БД наружу, если нет необходимости
    # ports:
    #   - "5433:5432"
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always