# .github/workflows/ci.yml

# Название рабочего процесса, которое будет отображаться в GitHub Actions
name: NestJS CI Pipeline

# Триггеры для запуска: push в main и pull request на main
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # Название задачи
  build-and-test:
    # Используем последнюю версию Ubuntu для запуска
    runs-on: ubuntu-latest

    # Стратегия для запуска тестов на нескольких версиях Node.js
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Настройка Node.js с использованием версии из матрицы (без кэширования)
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # 3. Включение Corepack для использования правильной версии Yarn
      - name: Enable Corepack
        run: corepack enable

      # 4. Ручная настройка кэша для Yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache yarn dependencies
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # 5. Установка зависимостей с использованием актуального флага
      - name: Install dependencies
        run: yarn install --immutable

      # 6. Создание .env файла для CI/CD
      # Эти переменные нужны для корректного запуска приложения во время тестов.
      # Используйте GitHub Secrets для реальных секретных данных.
      - name: Create .env file
        run: |
          echo "HTTP_PORT=3000" >> .env
          echo "HTTP_HOST=http://localhost:3000" >> .env
          # Добавьте сюда другие переменные, необходимые для тестов (например, DATABASE_URL)
          # echo "DATABASE_URL=postgresql://user:password@localhost:5432/test_db" >> .env
          echo "NODE_ENV=test" >> .env

      # 7. Запуск линтера для проверки стиля кода
      - name: Run linter
        run: yarn lint

      # 8. Запуск юнит-тестов
      - name: Run unit tests
        run: yarn test

      # 9. Запуск e2e-тестов
      # Если для e2e-тестов нужна база данных, ее можно поднять здесь с помощью Docker Compose
      # - name: Start services for e2e tests
      #   run: docker-compose -f docker-compose.test.yml up -d
      - name: Run e2e tests
        run: yarn test:e2e
      # - name: Stop services
      #   if: always()
      #   run: docker-compose -f docker-compose.test.yml down

      # 10. Сборка проекта для проверки, что все компилируется без ошибок
      - name: Build project
        run: yarn build