# .github/workflows/ci.yml

name: Docker CI & Security Scan (PR)

# Запускается на Pull Request в ветку 'main'.
on:
  pull_request:
    branches:
      - 'main'

jobs:
  # --- Задача 1: Сборка и сканирование Docker-образа ---
  # Используем тот же воркфлоу, что и в main.yml.
  # Он умный и не будет ПУШИТЬ образ, так как запускается в контексте PR.
  build:
    name: Build & Scan Docker Image
    uses: ./.github/workflows/reusable-docker-build.yml
    secrets: inherit

  # --- Задача 2: Запуск сканирования безопасности ---
  # Вызываем тот же воркфлоу, что и в node-ci.yml, для унификации.
  security:
    name: Security Scan
    uses: ./.github/workflows/reusable-security-scan.yml
    secrets: inherit