# .github/workflows/ci.yml

name: Docker CI & Security Scans (PR)

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Build & Scan Docker Image
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: X-MARIO/shared-workflows/.github/workflows/reusable-docker-build.yml@v1.0.0
    secrets: inherit

  sast:
    name: Security Analysis
    uses: X-MARIO/shared-workflows/.github/workflows/reusable-security-scan.yml@v1.0.0
    secrets: inherit

  secrets-scan:
    name: Gitleaks Secrets Scan
    uses: X-MARIO/shared-workflows/.github/workflows/reusable-gitleaks-scan.yml@v1.0.0
    secrets: inherit