# .github/workflows/node-ci.yml

name: Node.js CI & Security Scan (PR)

# Запускается на Pull Request в ветку 'main'.
on:
  pull_request:
    branches:
      - 'main'

jobs:
  # --- Задача 1: Запуск всех тестов через переиспользуемый воркфлоу ---
  tests:
    name: Build & Test
    uses: ./.github/workflows/reusable-node-tests.yml
    secrets: inherit

  # --- Задача 2: Запуск сканирования безопасности ---
  security:
    name: Security Scan
    uses: ./.github/workflows/reusable-security-scan.yml
    secrets: inherit